version: '3.7'
services:
  php:
    image: php:7.1.31
    volumes: 
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports: 
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0

  composer:
    image: composer:1.8.6
    volumes: 
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: composer install
